language: python
python:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
deploy:
  provider: pypi
  user: themattrix
  distributions: sdist bdist_wheel
  on:
    python: 2.7
    tags: true
    all_branches: true
    repo: themattrix/bashup
  password:
    secure: by5TIv+6ILWqNa3PQEGFavoJzxVNN4gfzfE+H0c3f1v8lB4cbLyU6XP+nQxfRpD1PGDuMaxM8iZ5qaLSCz9D9Ax51MLa5ReFax7FNsTQYjAT/BosXXBmZ/DWqt1hK1fhthx+8sa2Rnu/tzGCntWe1AEK0V0sKlrnqEiMWkHf3ao=
